# This is a basic workflow to help you get started with Actions

name: CI

# Controls when the workflow will run
on:
  # Triggers the workflow on push or pull request events but only for the main branch
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:

# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
  # This workflow contains a single job called "build"
  build:
    # The type of runner that the job will run on
    runs-on: debian-latest

    # Steps represent a sequence of tasks that will be executed as part of the job
    steps:
      # Checks-out your repository under $GITHUB_WORKSPACE, so your job can access it
      - uses: actions/checkout@v2

      # Runs a single command using the runners shell
      - name: Run a one-line script
        run: echo Hello, world!

      # Runs a set of commands using the runners shell
      - name: Run a multi-line script
        run: |
          echo Add other actions to build,
          echo test, and deploy your project.
        
      - name: init env
        run: |
          sudo apt update
          sudo apt install build-essential ccache ecj fastjar file g++ gawk \
          gettext git java-propose-classpath libelf-dev libncurses5-dev \
          libncursesw5-dev libssl-dev python python2.7-dev python3 unzip wget \
          python3-distutils python3-setuptools python3-dev rsync subversion \
          swig time xsltproc zlib1g-dev

      - name: clone
        env:
          REPO_URL: https://git.openwrt.org/openwrt/openwrt.git
          REPO_BRANCH: v19.07.9
        run: |
          git clone $REPO_URL -b $REPO_BRANCH
          
      - name: update feeds
        working-directory: ./openwrt
        run: |
          ./scripts/feeds update -a
          
      - name: install feeds
        working-directory: ./openwrt
        run: |
          ./scripts/feeds install -a
          
      - name: config
        env:
          CONFIG_FILE: ' .config'
        run: |
          mv $CONFIG_FILE openwrt/.config
          cd openwrt && make defconfig
          
      - name: download
        working-directory: ./openwrt
        run: |
          make download -j$(nproc)
          
      - name: build
        working-directory: ./openwrt
        run: |
          echo "$(nproc) thread build."
          make -j$(nproc) || make -j1 V=s
          
      - name: bin
        uses: actions/upload-artifact@main
        if: steps.c
        with:
          name: openwrt bin
          path: openwrt/bin
          
      - name: upload
        uses: actions/upload-artifact@main
        if: step success
        with:
          name: openwrt
          
      - name: gen release tag
        id: tag
        if: env
        run: |
          echo "::
          touch release.txt
          echo ""
          
      - name release
        uses: 
      
